In [16]:
import numpy as np
import gym
import time
import random
from IPython.display import clear_output

env = gym.make("FrozenLake-v0")

In [17]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
# print(q_table)

In [18]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_rate_decay = 0.001

In [19]:
reward_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()

    done = False
    reward_current_episode = 0

    for step in range(max_steps_per_episode):

        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate < exploration_rate_threshold:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        
        q_table[state,action] = q_table[state,action] * (1-learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))
        
        state = new_state
        reward_current_episode += reward

        if done == True:
            break

    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_rate_decay*episode)

    reward_all_episodes.append(reward_current_episode)

reward_per_thousand_episodes = np.split(np.array(reward_all_episodes),num_episodes/1000)
count = 1000
print("***Average reward per thousand episodes***")
for r in reward_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count+=1000

print("\n\n***Updated Q_table***\n")
print(q_table)

***Average reward per thousand episodes***
1000 :  0.04000000000000003
2000 :  0.20700000000000016
3000 :  0.3960000000000003
4000 :  0.5270000000000004
5000 :  0.6280000000000004
6000 :  0.6610000000000005
7000 :  0.6730000000000005
8000 :  0.6900000000000005
9000 :  0.6710000000000005
10000 :  0.7010000000000005


***Updated Q_table***

[[0.56337349 0.52119527 0.51839106 0.52335388]
 [0.30862927 0.30997164 0.30847182 0.5090556 ]
 [0.43329805 0.44394232 0.42778782 0.49525366]
 [0.19091106 0.37497061 0.30391197 0.48594928]
 [0.59157088 0.39959898 0.28661191 0.32059878]
 [0.         0.         0.         0.        ]
 [0.21714407 0.171497   0.23460294 0.09926643]
 [0.         0.         0.         0.        ]
 [0.34871711 0.48292331 0.35441216 0.64359758]
 [0.35289443 0.65811994 0.34812483 0.46412192]
 [0.60264692 0.46680649 0.36150928 0.20461787]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.53420834 0.36651127 0.78920025 0.5571229 ]
 

In [23]:
for episode in range(3):
    state = env.reset()
    done = False
    print("****EPISODE ",episode+1,"*******\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
#         print(info)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("**** You reached the goal! ***")
                time.sleep(3)
            else:
                print("**** You fell through a hole! ***")
                time.sleep(3)
                
            clear_output(wait=True)
            break
        
        state = new_state
        
env.close()
    

  (Down)
SFFF
FHFH
FFFH
HFFG
**** You reached the goal! ***
